#!/bin/sh
set -euf

# homebrew doesn't announce where it is in an
# environment variable
# so we're going to assume that reattach-to-user-namespace
# is in /usr/local/bin
# and then assume `brew --prefix`

brew=`which brew || :`
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

shellname=`basename "$SHELL"`

case "`uname`" in
    [dD]arwin)
        if [ -f reattach-to-user-namespace ]; then
            exec reattach-to-user-namespace -l "$shellname"
        else
            # assuming brew is on the path, we can get the bin directory this way
            $HOMEBREW_BIN="`$brew --prefix`"/bin
            if [ -f "$HOMEBREW_BIN"/reattach-to-user-namespace ]; then
                exec "$HOMEBREW_BIN"/reattach-to-user-namespace -l "$shellname"
            else
                # so this is probably an error because there's no
                # reattach-to-user-namespace executable in the 
                # expected location or a custom location
                exec "$shellname"
            fi
        fi
        ;;
    *)
        exec "$shellname"
        ;;
esac
