#!/bin/sh
set -euf

# homebrew doesn't announce where it is in an
# environment variable
# so we're going to assume that reattach-to-user-namespace
# is in /usr/local/bin
# and then assume `brew --prefix`

shellname="${SHELL##*/}"

case "$(uname)" in
    [dD]arwin)
        if [ -f /usr/local/bin/reattach-to-user-namespace ]; then
            exec /usr/local/binreattach-to-user-namespace -l "$shellname"
        else
            exec "$shellname"
        fi
        ;;
    *)
        exec "$shellname"
        ;;
esac
